title: "Alex Nugraha Setia"
description: "Personal academic portfolio — M.Sc. student site"
theme: null
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

google_analytics: "UA-XXXXXXXXX-X"

# multilingual config (simple)
default_lang: id
languages: ["id","en"]

# URL konfigurasi yang benar
url: "https://jiku1.github.io"
baseurl: "/Alex-Nugraha"

# agar post tanggal masa depan tetap muncul
future: true

# pastikan posts di-render sebagai halaman
collections:
  posts:
    output: true

paginate: 5
paginate_path: "/blog/page:num"
