title: "Alex Nugraha Setia"
description: "Personal academic portfolio — M.Sc. student site"
theme: null
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
# Google Analytics placeholder - replace with your measurement id or remove
google_analytics: "UA-XXXXXXXXX-X"

# multilingual config (simple)
default_lang: id
languages: ["id","en"]
url: "https://jiku1.github.io"
url: "https://jiku1.github.io"
baseurl: "/Alex-Nugraha"
